version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: automata_backend
    ports:
      - "5000:5000"
    environment:
      - OPENCLAW_WS_URL=ws://openclaw_instance:10424
    networks:
      - automata_net

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: automata_frontend
    ports:
      - "3000:3000" # Expone el puerto 3000 directamente
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://163.192.114.190:5000
    networks:
      - automata_net

networks:
  automata_net:
    driver: bridge
