version: '3.8'

services:
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: automata_backend
    ports:
      - "5000:5000"
    environment:
      # Inyectamos la URL y el Token para evitar hardcode en main.py
      - OPENCLAW_GATEWAY_URL=http://openclaw_instance:10424
      - OPENCLAW_TOKEN=8941487567606a620353868ebbcd32f73ba9b26de1551c09
    networks:
      - automata_net

  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: automata_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - automata_net

# Usamos la red externa donde corre OpenClaw
networks:
  automata_net:
    name: automataopenclaw_automata_net
    external: true
