version: '3.8'

services:
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: automata_backend
    ports:
      - "5000:5000"
    environment:
      # Usamos el nombre del contenedor de openclaw tal cual
      - OPENCLAW_API_URL=http://openclaw_instance:9001/api/v1/send
    networks:
      - automataopenclaw_automata_net

  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: automata_frontend
    ports:
      - "3000:3000" # Expone el puerto 3000 directamente
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://163.192.114.190:5000
    networks:
      - automataopenclaw_automata_net

# Declaramos la red externa a la que queremos unirnos
networks:
  automataopenclaw_automata_net:
    external: true
