version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"

    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - automata_net

networks:
  automata_net:
    external:
      name: automataopenclaw_automata_net
